# Generated by Django 4.1.3 on 2022-12-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Avatar', models.ImageField(null=True, upload_to='upload/CategoryProduct')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpDate', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Information', models.TextField()),
                ('DataTxt', models.TextField()),
                ('Price', models.IntegerField()),
                ('Avatar', models.ImageField(null=True, upload_to='upload/ListProduct')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpDate', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoryy', to='Data_Interaction.categoryproduct')),
            ],
            options={
                'unique_together': {('Name', 'Category')},
            },
        ),
    ]
