# Generated by Django 4.1.3 on 2022-12-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0002_categoryproduct_listproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100, null=True, unique=True)),
                ('Phone', models.CharField(max_length=100, null=True, unique=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
