# Generated by Django 4.1.3 on 2022-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0003_admininformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformation',
            name='Name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
