# Generated by Django 4.1.3 on 2022-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0004_admininformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
