# Generated by Django 4.1.3 on 2022-12-26 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0005_user_otp_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeBill', models.CharField(blank=True, max_length=200)),
                ('TimeToBuy', models.CharField(blank=True, max_length=200)),
                ('PaymentAmount', models.CharField(blank=True, max_length=200)),
                ('BuyData', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='UserLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlink', to=settings.AUTH_USER_MODEL),
        ),
    ]
