# Generated by Django 4.1.3 on 2022-12-26 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0006_personaltransactionhistory_categoryproduct_userlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='UserLink',
        ),
        migrations.AddField(
            model_name='personaltransactionhistory',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personaltransactionhistory',
            name='UserLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlink', to=settings.AUTH_USER_MODEL),
        ),
    ]
