# Generated by Django 4.1.3 on 2022-12-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0007_remove_categoryproduct_userlink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltransactionhistory',
            old_name='CodeBill',
            new_name='CodeOrders',
        ),
    ]
