# Generated by Django 4.1.3 on 2022-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0008_rename_codebill_personaltransactionhistory_codeorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltransactionhistory',
            name='TimeToBuy',
        ),
        migrations.AddField(
            model_name='personaltransactionhistory',
            name='TransactionTime',
            field=models.DateTimeField(auto_now_add=True, max_length=200, null=True),
        ),
    ]
