# Generated by Django 4.1.3 on 2022-12-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0009_remove_personaltransactionhistory_timetobuy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltransactionhistory',
            name='CodeOrders',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
