# Generated by Django 4.1.3 on 2023-01-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0011_bankinformation_alter_categoryproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankinformation',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
