# Generated by Django 4.1.3 on 2023-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0012_alter_bankinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinformation',
            name='AccountName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
