# Generated by Django 4.1.3 on 2023-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0014_bankinformation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformation',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/AdminInformation'),
        ),
        migrations.AddField(
            model_name='admininformation',
            name='BrandName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admininformation',
            name='Phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
