# Generated by Django 4.1.3 on 2023-01-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0016_rename_accountname_bankinformation_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admininformation',
            old_name='BrandName',
            new_name='Brand_Name',
        ),
        migrations.RenameField(
            model_name='bankinformation',
            old_name='AccountNumber',
            new_name='Account_Number',
        ),
        migrations.RenameField(
            model_name='bankinformation',
            old_name='BankName',
            new_name='Bank_Name',
        ),
        migrations.RenameField(
            model_name='bankinformation',
            old_name='MainColor',
            new_name='Main_Color',
        ),
        migrations.RenameField(
            model_name='bankinformation',
            old_name='QRCodeLink',
            new_name='QR_Code_Link',
        ),
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='CreateDate',
            new_name='Create_Date',
        ),
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='UpDate',
            new_name='Up_Date',
        ),
        migrations.RenameField(
            model_name='listproduct',
            old_name='CreateDate',
            new_name='Create_Date',
        ),
        migrations.RenameField(
            model_name='listproduct',
            old_name='DataTxt',
            new_name='Data_Txt',
        ),
        migrations.RenameField(
            model_name='listproduct',
            old_name='UpDate',
            new_name='Up_Date',
        ),
        migrations.RenameField(
            model_name='personaltransactionhistory',
            old_name='BuyData',
            new_name='Buy_Data',
        ),
        migrations.RenameField(
            model_name='personaltransactionhistory',
            old_name='CodeOrders',
            new_name='Code_Orders',
        ),
        migrations.RenameField(
            model_name='personaltransactionhistory',
            old_name='PaymentAmount',
            new_name='Payment_Amount',
        ),
        migrations.RenameField(
            model_name='personaltransactionhistory',
            old_name='TransactionTime',
            new_name='Transaction_Time',
        ),
        migrations.RenameField(
            model_name='personaltransactionhistory',
            old_name='UserLink',
            new_name='User_Link',
        ),
    ]
