# Generated by Django 4.1.3 on 2023-01-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0017_rename_brandname_admininformation_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinformation',
            name='Short_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankinformation',
            name='Main_Color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
