# Generated by Django 4.1.3 on 2023-01-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0018_bankinformation_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltransactionhistory',
            name='Content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personaltransactionhistory',
            name='Status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
