# Generated by Django 4.1.3 on 2023-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0019_personaltransactionhistory_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformation',
            name='Main_Color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
