# Generated by Django 4.1.3 on 2023-01-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0020_admininformation_main_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinformation',
            name='Api_Key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankinformation',
            name='Code_Api_Key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
