# Generated by Django 4.1.3 on 2023-01-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0021_bankinformation_api_key_bankinformation_code_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinformation',
            name='Api_Key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
