# Generated by Django 4.1.3 on 2023-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0024_rename_avatar_listproduct_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproduct',
            name='Data_Txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
