# Generated by Django 4.1.3 on 2023-01-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0025_alter_listproduct_data_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltransactionhistory',
            name='Transaction_Time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
