# Generated by Django 4.1.3 on 2023-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0026_alter_personaltransactionhistory_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Total_recharge_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
