# Generated by Django 4.1.3 on 2023-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0027_user_total_recharge_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltransactionhistory',
            name='Transaction_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
