# Generated by Django 4.1.3 on 2023-02-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0029_alter_personaltransactionhistory_buy_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltransactionhistory',
            name='Buy_Data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
