# Generated by Django 4.1.3 on 2023-02-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0030_alter_personaltransactionhistory_buy_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='Total_amount_deducted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
