# Generated by Django 4.1.3 on 2023-02-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0035_cryptoinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoinformation',
            name='Avatar_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/Crypto'),
        ),
        migrations.AddField(
            model_name='cryptoinformation',
            name='Short_Name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptoinformation',
            name='Avatar_QR_Code',
            field=models.ImageField(blank=True, null=True, upload_to='upload/Crypto'),
        ),
    ]
