# Generated by Django 4.1.3 on 2023-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Interaction', '0037_cryptoinformation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinformation',
            name='Background_Color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
